name: build jupyterhub image
on:
  workflow_run:
    workflows: [update conda lockfile]
    types:
      - completed
  push:
    paths:
      - .github/workflows/repo2docker.yaml
      # files used by binder/appendix
      - conda/conda-lock.yml
      # files used by repo2docker, in order of use
      - binder/apt.txt
      - binder/environment.yml
      - binder/start
      - binder/appendix
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout files in repo
      uses: actions/checkout@main
    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{github.actor}}
        DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
        DOCKER_REGISTRY: ghcr.io
        IMAGE_NAME: nmfs-opensci/test-image
        APPENDIX_FILE: binder/appendix
